const tools = [
  // Backend
  {
    name: "Rust",
    url: "/assets/icons/rust.svg",
    radius: 70,
    bg: "#0b7261",
  },
  {
    name: "Go",
    url: "/assets/icons/go.svg",
    radius: 55,
    bg: "#ffffff",
  },
  {
    name: "PHP",
    url: "/assets/icons/php.svg",
    radius: 55,
    bg: "#4f5b93",
  },
  {
    name: "Zig",
    url: "/assets/icons/zig.svg",
    radius: 50,
    bg: "#111111",
  },
  {
    name: "C",
    url: "/assets/icons/c.svg",
    radius: 40,
    bg: "#1c1b22",
  },
  {
    name: "Ruby",
    url: "/assets/icons/ruby.svg",
    radius: 35,
    bg: "#1c1917",
  },
  {
    name: "Kotlin",
    url: "/assets/icons/kotlin.png",
    radius: 40,
    bg: "#19191c",
  },
  {
    name: "Python",
    url: "/assets/icons/python.svg",
    radius: 25,
    bg: "#1e415d",
  },
  {
    name: "Java",
    url: "/assets/icons/java.svg",
    radius: 20,
    bg: "#f5f5f6",
  },
  {
    name: "C#",
    url: "/assets/icons/csharp.svg",
    radius: 25,
    bg: "#1f1f1f",
  },
  // Frontend
  {
    name: "HTML",
    url: "/assets/icons/html.svg",
    radius: 40,
    bg: "#e7632b",
  },
  {
    name: "CSS",
    url: "/assets/icons/css.svg",
    radius: 40,
    bg: "#663399",
  },
  {
    name: "jQuery",
    url: "/assets/icons/jquery.svg",
    radius: 40,
    bg: "#78cff5",
  },
  {
    name: "Tailwind",
    url: "/assets/icons/tailwind.svg",
    radius: 25,
    bg: "#030712",
  },
  {
    name: "JavaScript",
    url: "/assets/icons/javascript.png",
    radius: 10,
    bg: "#efd81c",
  },
  // Full Stack
  {
    name: "SvelteKit",
    url: "/assets/icons/sveltekit.svg",
    radius: 50,
    bg: "#23272f",
  },
  {
    name: "TypeScript",
    url: "/assets/icons/typescript.svg",
    radius: 25,
    bg: "#3178c6",
  },
  {
    name: "Rails",
    url: "/assets/icons/rails.svg",
    radius: 35,
    bg: "#ffffff",
  },
  {
    name: "Laravel",
    url: "/assets/icons/laravel.svg",
    radius: 40,
    bg: "#ffffff",
  },
  { name: "Astro", url: "/assets/icons/astro.svg", radius: 25, bg: "#ffffff" },
  // Databases
  {
    name: "SQLite",
    url: "/assets/icons/sqlite.svg",
    radius: 45,
    bg: "#93d1ee",
  },
  {
    name: "Postgres",
    url: "/assets/icons/postgres.svg",
    radius: 55,
    bg: "#212121",
  },
  {
    name: "MariaDB",
    url: "/assets/icons/mariadb.svg",
    radius: 50,
    bg: "#c0765a",
  },
  {
    name: "MySQL",
    url: "/assets/icons/mysql.svg",
    radius: 40,
    bg: "#ffffff",
  },
  {
    name: "MongoDB",
    url: "/assets/icons/mongodb.png",
    radius: 20,
    bg: "#001e2b",
  },
  // Game Development
  {
    name: "Godot",
    url: "/assets/icons/godot.svg",
    radius: 70,
    bg: "#2d3248",
  },
  {
    name: "Bevy",
    url: "/assets/icons/bevy.png",
    radius: 35,
    bg: "#1e1e22",
  },
  {
    name: "Blender",
    url: "/assets/icons/blender.svg",
    radius: 40,
    bg: "#ffffff",
  },
  {
    name: "GameMaker",
    url: "/assets/icons/gamemaker.svg",
    radius: 40,
    bg: "#ffffff",
  },
  { name: "Unity", url: "/assets/icons/unity.svg", radius: 25, bg: "#ffffff" },
  // Shells
  {
    name: "Fish",
    url: "/assets/icons/fish.png",
    radius: 70,
    bg: "#202028",
  },
  {
    name: "Nushell",
    url: "/assets/icons/nushell.svg",
    radius: 55,
    bg: "#1b1b1f",
  },
  {
    name: "Zsh",
    url: "/assets/icons/zsh.svg",
    radius: 40,
    bg: "#ffffff",
  },
  {
    name: "Bash",
    url: "/assets/icons/bash.svg",
    radius: 25,
    bg: "#a32d2a",
  },
  {
    name: "PowerShell",
    url: "/assets/icons/powershell.png",
    radius: 10,
    bg: "#1f1f1f",
  },
  // Operating Systems
  {
    name: "Arch",
    url: "/assets/icons/arch.svg",
    radius: 85,
    bg: "#333333",
  },
  {
    name: "Ubuntu",
    url: "/assets/icons/ubuntu.svg",
    radius: 45,
    bg: "#262626",
  },
  {
    name: "Mint",
    url: "/assets/icons/mint.svg",
    radius: 45,
    bg: "#69b53f",
  },
  {
    name: "Debian",
    url: "/assets/icons/debian.svg",
    radius: 40,
    bg: "#e8e9ee",
  },
  {
    name: "Android",
    url: "/assets/icons/android.svg",
    radius: 45,
    bg: "#f5f5f5",
  },
  {
    name: "Windows",
    url: "/assets/icons/windows.svg",
    radius: 10,
    bg: "#0067b8",
  },
  {
    name: "OSX",
    url: "/assets/icons/osx.svg",
    radius: 25,
    bg: "#348bd2",
  },
  // Editors
  {
    name: "Helix",
    url: "/assets/icons/helix.svg",
    radius: 100,
    bg: "#28153b",
  },
  {
    name: "Neovim",
    url: "/assets/icons/neovim.svg",
    radius: 55,
    bg: "#0f191f",
  },
  {
    name: "Vim",
    url: "/assets/icons/vim.svg",
    radius: 50,
    bg: "#cccc99",
  },
  {
    name: "VSCode",
    url: "/assets/icons/vscode.svg",
    radius: 30,
    bg: "#0d1014",
  },
  {
    name: "Android Studio",
    url: "/assets/icons/androidstudio.svg",
    radius: 25,
    bg: "#2b2d30",
  },
  {
    name: "JetBrains",
    url: "/assets/icons/jetbrains.svg",
    radius: 20,
    bg: "#19191c",
  },
  // Data Structuring
  {
    name: "JSON",
    url: "/assets/icons/json.svg",
    radius: 20,
    bg: "#faf0e6",
  },
  {
    name: "TOML",
    url: "/assets/icons/toml.svg",
    radius: 70,
    bg: "#f6f2ea",
  },
  // Other
  { name: "Tauri", url: "/assets/icons/tauri.svg", radius: 40, bg: "#1b1a18" },
  {
    name: "WASM",
    url: "/assets/icons/wasm.svg",
    radius: 70,
    bg: "#654ff0",
  },
  {
    name: "Appwrite",
    url: "/assets/icons/appwrite.svg",
    radius: 40,
    bg: "#2c2c30",
  },
  {
    name: "Flutter",
    url: "/assets/icons/flutter.svg",
    radius: 35,
    bg: "#041e3c",
  },
  {
    name: "Lua",
    url: "/assets/icons/lua.svg",
    radius: 25,
    bg: "#ffffff",
  },
];
