const tools = [
  // Backend
  {
    name: "Rust",
    url: "/assets/icons/rust.svg",
    radius: 70,
    bg: "#ffc832",
  },
  {
    name: "Go",
    url: "/assets/icons/go.svg",
    radius: 55,
    bg: "#003F50",
  },
  {
    name: "PHP",
    url: "/assets/icons/php.svg",
    radius: 55,
    bg: "#272940",
  },
  {
    name: "Zig",
    url: "/assets/icons/zig.svg",
    radius: 50,
    bg: "#4A3100",
  },
  {
    name: "C",
    url: "/assets/icons/c.svg",
    radius: 40,
    bg: "#2A3540",
  },
  {
    name: "Ruby",
    url: "/assets/icons/ruby.svg",
    radius: 35,
    bg: "#4A1410",
  },
  {
    name: "Kotlin",
    url: "/assets/icons/kotlin.png",
    radius: 40,
    bg: "#2A1A60",
  },
  {
    name: "Python",
    url: "/assets/icons/python.svg",
    radius: 25,
    bg: "#142840",
  },
  {
    name: "Java",
    url: "/assets/icons/java.svg",
    radius: 20,
    bg: "#4A2C00",
  },
  {
    name: "C#",
    url: "/assets/icons/csharp.svg",
    radius: 25,
    bg: "#0D360C",
  },
  // Frontend
  {
    name: "HTML",
    url: "/assets/icons/html.svg",
    radius: 40,
    bg: "#4A1A0C",
  },
  {
    name: "CSS",
    url: "/assets/icons/css.svg",
    radius: 40,
    bg: "#082A45",
  },
  {
    name: "jQuery",
    url: "/assets/icons/jquery.svg",
    radius: 40,
    bg: "#032840",
  },
  {
    name: "Tailwind",
    url: "/assets/icons/tailwind.svg",
    radius: 25,
    bg: "#023A44",
  },
  {
    name: "JavaScript",
    url: "/assets/icons/javascript.png",
    radius: 10,
    bg: "#4A4200",
  },
  // Full Stack
  {
    name: "SvelteKit",
    url: "/assets/icons/sveltekit.svg",
    radius: 50,
    bg: "#4A1200",
  },
  {
    name: "TypeScript",
    url: "/assets/icons/typescript.svg",
    radius: 25,
    bg: "#102840",
  },
  {
    name: "Rails",
    url: "/assets/icons/rails.svg",
    radius: 35,
    bg: "#400000",
  },
  {
    name: "Laravel",
    url: "/assets/icons/laravel.svg",
    radius: 40,
    bg: "#4A0E0A",
  },
  { name: "Astro", url: "/assets/icons/astro.svg", radius: 25, bg: "#4A1D00" },
  // Databases
  {
    name: "SQLite",
    url: "/assets/icons/sqlite.svg",
    radius: 45,
    bg: "#022535",
  },
  {
    name: "Postgres",
    url: "/assets/icons/postgres.svg",
    radius: 55,
    bg: "#142840",
  },
  {
    name: "MariaDB",
    url: "/assets/icons/mariadb.svg",
    radius: 50,
    bg: "#001E28",
  },
  {
    name: "MySQL",
    url: "/assets/icons/mysql.svg",
    radius: 40,
    bg: "#182E40",
  },
  {
    name: "MongoDB",
    url: "/assets/icons/mongodb.svg",
    radius: 20,
    bg: "#183D18",
  },
  // Game Development
  {
    name: "Godot",
    url: "/assets/icons/godot.svg",
    radius: 70,
    bg: "#18304A",
  },
  {
    name: "Bevy",
    url: "/assets/icons/bevy.png",
    radius: 35,
    bg: "#181820",
  },
  {
    name: "Blender",
    url: "/assets/icons/blender.svg",
    radius: 40,
    bg: "#4A2800",
  },
  {
    name: "GameMaker",
    url: "/assets/icons/gamemaker.svg",
    radius: 40,
    bg: "#6882fb",
  },
  { name: "Unity", url: "/assets/icons/unity.svg", radius: 25, bg: "#1A1A1A" },
  // Shells
  {
    name: "Fish",
    url: "/assets/icons/fish.png",
    radius: 70,
    bg: "#4A1F16",
  },
  {
    name: "Nushell",
    url: "/assets/icons/nushell.svg",
    radius: 55,
    bg: "#182E32",
  },
  {
    name: "Zsh",
    url: "/assets/icons/zsh.svg",
    radius: 40,
    bg: "#3A4008",
  },
  {
    name: "Bash",
    url: "/assets/icons/bash.svg",
    radius: 25,
    bg: "#293137",
  },
  {
    name: "PowerShell",
    url: "/assets/icons/powershell.png",
    radius: 10,
    bg: "#012456",
  },
  // Operating Systems
  {
    name: "Arch",
    url: "/assets/icons/arch.svg",
    radius: 85,
    bg: "#083650",
  },
  {
    name: "Ubuntu",
    url: "/assets/icons/ubuntu.svg",
    radius: 45,
    bg: "#4A1B0A",
  },
  {
    name: "Mint",
    url: "/assets/icons/mint.svg",
    radius: 45,
    bg: "#2A4010",
  },
  {
    name: "Debian",
    url: "/assets/icons/debian.svg",
    radius: 40,
    bg: "#380B12",
  },
  {
    name: "Android",
    url: "/assets/icons/android.svg",
    radius: 45,
    bg: "#104828",
  },
  {
    name: "Windows",
    url: "/assets/icons/windows.svg",
    radius: 10,
    bg: "#002850",
  },
  {
    name: "OSX",
    url: "/assets/icons/osx.svg",
    radius: 25,
    bg: "#282828",
  },
  // Editors
  {
    name: "Helix",
    url: "/assets/icons/helix.svg",
    radius: 100,
    bg: "#28153b",
  },
  {
    name: "Neovim",
    url: "/assets/icons/neovim.svg",
    radius: 55,
    bg: "#1E3818",
  },
  {
    name: "Vim",
    url: "/assets/icons/vim.svg",
    radius: 50,
    bg: "#004A18",
  },
  {
    name: "VSCode",
    url: "/assets/icons/vscode.svg",
    radius: 30,
    bg: "#003050",
  },
  {
    name: "Android Studio",
    url: "/assets/icons/androidstudio.svg",
    radius: 25,
    bg: "#104828",
  },
  {
    name: "JetBrains",
    url: "/assets/icons/jetbrains.svg",
    radius: 20,
    bg: "#0D0D1A",
  },
  // Data Structuring
  {
    name: "JSON",
    url: "/assets/icons/json.svg",
    radius: 20,
    bg: "#131416",
  },
  {
    name: "TOML",
    url: "/assets/icons/toml.svg",
    radius: 70,
    bg: "#f6f2ea",
  },
  // Other
  { name: "Tauri", url: "/assets/icons/tauri.svg", radius: 40, bg: "#4A3800" },
  {
    name: "WASM",
    url: "/assets/icons/wasm.svg",
    radius: 70,
    bg: "#1E1460",
  },
  {
    name: "Appwrite",
    url: "/assets/icons/appwrite.svg",
    radius: 40,
    bg: "#2c2c30",
  },
  {
    name: "Flutter",
    url: "/assets/icons/flutter.svg",
    radius: 35,
    bg: "#103C50",
  },
  {
    name: "Lua",
    url: "/assets/icons/lua.svg",
    radius: 25,
    bg: "#000050",
  },
];
