const tools = [
  // Backend
  {
    name: "Rust",
    url: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Rust_programming_language_black_logo.svg",
    radius: 70,
    bg: "#ffc832",
  },
  {
    name: "Go",
    url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Go_Logo_Blue.svg",
    radius: 55,
    bg: "#003F50",
  },
  {
    name: "Zig",
    url: "https://upload.wikimedia.org/wikipedia/commons/8/83/Zig-logomark-2024.svg",
    radius: 50,
    bg: "#4A3100",
  },
  {
    name: "C",
    url: "https://upload.wikimedia.org/wikipedia/commons/1/18/C_Programming_Language.svg",
    radius: 40,
    bg: "#2A3540",
  },
  {
    name: "Ruby",
    url: "https://upload.wikimedia.org/wikipedia/commons/7/73/Ruby_logo.svg",
    radius: 35,
    bg: "#4A1410",
  },
  {
    name: "Kotlin",
    url: "https://upload.wikimedia.org/wikipedia/commons/7/74/Kotlin_Icon.png",
    radius: 40,
    bg: "#2A1A60",
  },
  {
    name: "Python",
    url: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg",
    radius: 25,
    bg: "#142840",
  },
  {
    name: "PHP",
    url: "https://upload.wikimedia.org/wikipedia/commons/2/27/PHP-logo.svg",
    radius: 35,
    bg: "#272940",
  },
  {
    name: "Java",
    url: "https://upload.wikimedia.org/wikipedia/en/3/30/Java_programming_language_logo.svg",
    radius: 20,
    bg: "#4A2C00",
  },
  {
    name: "C#",
    url: "https://upload.wikimedia.org/wikipedia/commons/f/ff/C-Sharp_Logo.svg",
    radius: 25,
    bg: "#0D360C",
  },
  // Frontend
  {
    name: "HTML",
    url: "https://upload.wikimedia.org/wikipedia/commons/6/61/HTML5_logo_and_wordmark.svg",
    radius: 40,
    bg: "#4A1A0C",
  },
  {
    name: "CSS",
    url: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Official_CSS_Logo.svg",
    radius: 40,
    bg: "#082A45",
  },
  {
    name: "jQuery",
    url: "/assets/icons/jquery.svg",
    radius: 40,
    bg: "#032840",
  },
  {
    name: "Tailwind",
    url: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Tailwind_CSS_Logo.svg",
    radius: 25,
    bg: "#023A44",
  },
  {
    name: "JavaScript",
    url: "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
    radius: 10,
    bg: "#4A4200",
  },
  // Full Stack
  {
    name: "SvelteKit",
    url: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Svelte_Logo.svg",
    radius: 50,
    bg: "#4A1200",
  },
  {
    name: "TypeScript",
    url: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg",
    radius: 25,
    bg: "#102840",
  },
  {
    name: "Rails",
    url: "https://upload.wikimedia.org/wikipedia/commons/6/62/Ruby_On_Rails_Logo.svg",
    radius: 35,
    bg: "#400000",
  },
  {
    name: "Laravel",
    url: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Laravel.svg",
    radius: 40,
    bg: "#4A0E0A",
  },
  { name: "Astro", url: "/assets/icons/astro.svg", radius: 25, bg: "#4A1D00" },
  // Databases
  {
    name: "SQLite",
    url: "https://upload.wikimedia.org/wikipedia/commons/9/97/Sqlite-square-icon.svg",
    radius: 45,
    bg: "#022535",
  },
  {
    name: "Postgres",
    url: "https://upload.wikimedia.org/wikipedia/commons/2/29/Postgresql_elephant.svg",
    radius: 55,
    bg: "#142840",
  },
  {
    name: "MariaDB",
    url: "https://mariadb.com/wp-content/uploads/2019/11/mariadb-logo-vertical_blue.svg",
    radius: 50,
    bg: "#001E28",
  },
  {
    name: "MySQL",
    url: "https://upload.wikimedia.org/wikipedia/en/d/dd/MySQL_logo.svg",
    radius: 40,
    bg: "#182E40",
  },
  {
    name: "MongoDB",
    url: "https://upload.wikimedia.org/wikipedia/commons/9/93/MongoDB_Logo.svg",
    radius: 20,
    bg: "#183D18",
  },
  // Game Development
  {
    name: "Godot",
    url: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Godot_icon.svg",
    radius: 70,
    bg: "#18304A",
  },
  {
    name: "Bevy",
    url: "/assets/icons/bevy.png",
    radius: 35,
    bg: "#181820",
  },
  {
    name: "Blender",
    url: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Blender_logo_no_text.svg",
    radius: 40,
    bg: "#4A2800",
  },
  {
    name: "GameMaker",
    url: "https://www.svgrepo.com/show/373756/light-gamemaker2.svg",
    radius: 40,
    bg: "#6882fb",
  },
  { name: "Unity", url: "/assets/icons/unity.svg", radius: 25, bg: "#1A1A1A" },
  // Shells
  {
    name: "Fish",
    url: "https://upload.wikimedia.org/wikipedia/commons/3/39/Fish_icon.png",
    radius: 70,
    bg: "#4A1F16",
  },
  {
    name: "Nushell",
    url: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Logo_of_nushell_shell.svg",
    radius: 55,
    bg: "#182E32",
  },
  {
    name: "Zsh",
    url: "https://upload.wikimedia.org/wikipedia/commons/7/75/Z_Shell_Logo_Color_Vertical.svg",
    radius: 40,
    bg: "#3A4008",
  },
  {
    name: "Bash",
    url: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Bash_Logo_Colored.svg",
    radius: 25,
    bg: "#293137",
  },
  {
    name: "PowerShell",
    url: "https://upload.wikimedia.org/wikipedia/commons/a/af/PowerShell_Core_6.0_icon.png",
    radius: 10,
    bg: "#012456",
  },
  // Operating Systems
  {
    name: "Arch",
    url: "https://upload.wikimedia.org/wikipedia/commons/1/13/Arch_Linux_%22Crystal%22_icon.svg",
    radius: 85,
    bg: "#083650",
  },
  {
    name: "Ubuntu",
    url: "https://upload.wikimedia.org/wikipedia/commons/9/9e/UbuntuCoF.svg",
    radius: 45,
    bg: "#4A1B0A",
  },
  {
    name: "Mint",
    url: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Linux_Mint_logo_without_wordmark.svg",
    radius: 45,
    bg: "#2A4010",
  },
  {
    name: "Debian",
    url: "https://upload.wikimedia.org/wikipedia/commons/6/66/Openlogo-debianV2.svg",
    radius: 40,
    bg: "#380B12",
  },
  {
    name: "Android",
    url: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Android_robot.svg",
    radius: 45,
    bg: "#104828",
  },
  {
    name: "Windows",
    url: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Windows_logo_-_2012.svg",
    radius: 10,
    bg: "#002850",
  },
  {
    name: "OSX",
    url: "https://upload.wikimedia.org/wikipedia/commons/3/30/MacOS_logo.svg",
    radius: 25,
    bg: "#282828",
  },
  // Editors
  {
    name: "Helix",
    url: "https://helix-editor.com/logo.svg",
    radius: 100,
    bg: "#28153b",
  },
  {
    name: "Neovim",
    url: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Neovim-mark.svg",
    radius: 55,
    bg: "#1E3818",
  },
  {
    name: "Vim",
    url: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Vimlogo.svg",
    radius: 50,
    bg: "#004A18",
  },
  {
    name: "VSCode",
    url: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Visual_Studio_Code_1.35_icon.svg",
    radius: 30,
    bg: "#003050",
  },
  {
    name: "Android Studio",
    icon: "androidstudio",
    variant: "plain",
    radius: 25,
    bg: "#104828",
  },
  {
    name: "JetBrains",
    icon: "jetbrains",
    variant: "plain",
    radius: 20,
    bg: "#0D0D1A",
  },
  // Data Structuring
  {
    name: "JSON",
    icon: "json",
    variant: "plain",
    radius: 20,
    bg: "#131416",
  },
  {
    name: "TOML",
    url: "https://www.svgrepo.com/show/374133/toml.svg",
    radius: 70,
    bg: "#f6f2ea",
  },
  // Other
  { name: "Tauri", icon: "tauri", variant: "plain", radius: 40, bg: "#4A3800" },
  {
    name: "WASM",
    icon: "wasm",
    variant: "original",
    radius: 70,
    bg: "#1E1460",
  },
  {
    name: "Appwrite",
    icon: "appwrite",
    variant: "original",
    radius: 40,
    bg: "#4A0E22",
  },
  {
    name: "Flutter",
    icon: "flutter",
    variant: "plain",
    radius: 35,
    bg: "#103C50",
  },
  { name: "Lua", icon: "lua", variant: "plain", radius: 25, bg: "#000050" },
];
