const tools = [
  // Backend
  {
    name: "Rust",
    icon: "rust",
    variant: "original",
    radius: 70,
    bg: "#4A1810",
  },
  { name: "Go", icon: "go", variant: "plain", radius: 55, bg: "#003F50" },
  { name: "Zig", icon: "zig", variant: "original", radius: 50, bg: "#4A3100" },
  { name: "C", icon: "c", variant: "original", radius: 40, bg: "#2A3540" },
  { name: "Ruby", icon: "ruby", variant: "plain", radius: 35, bg: "#4A1410" },
  {
    name: "Kotlin",
    icon: "kotlin",
    variant: "plain",
    radius: 40,
    bg: "#2A1A60",
  },
  {
    name: "Python",
    icon: "python",
    variant: "plain",
    radius: 25,
    bg: "#142840",
  },
  { name: "PHP", icon: "php", variant: "plain", radius: 35, bg: "#272940" },
  { name: "Java", icon: "java", variant: "plain", radius: 20, bg: "#4A2C00" },
  { name: "C#", icon: "csharp", variant: "plain", radius: 25, bg: "#0D360C" },
  // Frontend
  { name: "HTML", icon: "html5", variant: "plain", radius: 40, bg: "#4A1A0C" },
  { name: "CSS", icon: "css3", variant: "plain", radius: 40, bg: "#082A45" },
  {
    name: "jQuery",
    icon: "jquery",
    variant: "plain",
    radius: 30,
    bg: "#032840",
  },
  {
    name: "Tailwind",
    icon: "tailwindcss",
    variant: "original",
    radius: 25,
    bg: "#023A44",
  },
  {
    name: "JavaScript",
    icon: "javascript",
    variant: "plain",
    radius: 10,
    bg: "#4A4200",
  },
  // Full Stack
  {
    name: "SvelteKit",
    icon: "svelte",
    variant: "plain",
    radius: 50,
    bg: "#4A1200",
  },
  {
    name: "TypeScript",
    icon: "typescript",
    variant: "plain",
    radius: 25,
    bg: "#102840",
  },
  { name: "Rails", icon: "rails", variant: "plain", radius: 35, bg: "#400000" },
  {
    name: "Laravel",
    icon: "laravel",
    variant: "original",
    radius: 40,
    bg: "#4A0E0A",
  },
  { name: "Astro", icon: "astro", variant: "plain", radius: 25, bg: "#4A1D00" },
  // Databases
  {
    name: "SQLite",
    icon: "sqlite",
    variant: "plain",
    radius: 45,
    bg: "#022535",
  },
  {
    name: "Postgres",
    icon: "postgresql",
    variant: "plain",
    radius: 55,
    bg: "#142840",
  },
  {
    name: "MariaDB",
    icon: "mariadb",
    variant: "original",
    radius: 50,
    bg: "#001E28",
  },
  {
    name: "MySQL",
    icon: "mysql",
    variant: "original",
    radius: 40,
    bg: "#182E40",
  },
  {
    name: "MongoDB",
    icon: "mongodb",
    variant: "plain",
    radius: 40,
    bg: "#183D18",
  },
  // Game Development
  { name: "Godot", icon: "godot", variant: "plain", radius: 70, bg: "#18304A" },
  {
    name: "Bevy",
    icon: "bevyengine",
    variant: "plain",
    radius: 35,
    bg: "#181820",
  },
  {
    name: "Blender",
    icon: "blender",
    variant: "original",
    radius: 40,
    bg: "#4A2800",
  },
  { name: "GameMaker", emoji: "🎮️", radius: 40, bg: "#2D4014" },
  { name: "Unity", icon: "unity", variant: "plain", radius: 25, bg: "#1A1A1A" },
  // Shells
  { name: "Fish", emoji: "🐟️", radius: 70, bg: "#4A1F16" },
  { name: "Nushell", emoji: "🐚", radius: 55, bg: "#182E32" },
  { name: "Zsh", icon: "zsh", variant: "plain", radius: 40, bg: "#3A4008" },
  { name: "Bash", icon: "bash", variant: "plain", radius: 25, bg: "#293137" },
  {
    name: "PowerShell",
    icon: "powershell",
    variant: "plain",
    radius: 10,
    bg: "#012456",
  },
  // Operating Systems
  {
    name: "Arch",
    icon: "archlinux",
    variant: "plain",
    radius: 85,
    bg: "#083650",
  },
  {
    name: "Ubuntu",
    icon: "ubuntu",
    variant: "plain",
    radius: 45,
    bg: "#4A1B0A",
  },
  {
    name: "Mint",
    icon: "linuxmint",
    variant: "plain",
    radius: 45,
    bg: "#2A4010",
  },
  {
    name: "Debian",
    icon: "debian",
    variant: "plain",
    radius: 40,
    bg: "#380B12",
  },
  {
    name: "Android",
    icon: "android",
    variant: "plain",
    radius: 45,
    bg: "#104828",
  },
  {
    name: "Windows",
    icon: "windows8",
    variant: "original",
    radius: 10,
    bg: "#002850",
  },
  {
    name: "OSX",
    icon: "apple",
    variant: "original",
    radius: 25,
    bg: "#282828",
  },
  // Editors
  { name: "Helix", emoji: "🧬", radius: 100, bg: "#28104A" },
  {
    name: "Neovim",
    icon: "neovim",
    variant: "plain",
    radius: 55,
    bg: "#1E3818",
  },
  { name: "Vim", icon: "vim", variant: "plain", radius: 50, bg: "#004A18" },
  {
    name: "VSCode",
    icon: "vscode",
    variant: "plain",
    radius: 40,
    bg: "#003050",
  },
  {
    name: "Android Studio",
    icon: "androidstudio",
    variant: "plain",
    radius: 25,
    bg: "#104828",
  },
  {
    name: "JetBrains",
    icon: "jetbrains",
    variant: "plain",
    radius: 20,
    bg: "#0D0D1A",
  },
  // Other
  { name: "Tauri", icon: "tauri", variant: "plain", radius: 40, bg: "#4A3800" },
  {
    name: "WASM",
    icon: "wasm",
    variant: "original",
    radius: 70,
    bg: "#1E1460",
  },
  {
    name: "Appwrite",
    icon: "appwrite",
    variant: "original",
    radius: 40,
    bg: "#4A0E22",
  },
  {
    name: "Flutter",
    icon: "flutter",
    variant: "plain",
    radius: 35,
    bg: "#103C50",
  },
  { name: "Lua", icon: "lua", variant: "plain", radius: 25, bg: "#000050" },
];
