const tools = [
  // Backend
  {
    name: "Rust",
    icon: "rust",
    variant: "original",
    radius: 30,
    bg: "#CE412B",
    fg: "#FFFFFF",
  },
  {
    name: "Go",
    icon: "go",
    variant: "plain",
    radius: 30,
    bg: "#00ACD7",
    fg: "#FFFFFF",
  },
  {
    name: "Zig",
    icon: "zig",
    variant: "original",
    radius: 30,
    bg: "#F7A41D",
    fg: "#FFFFFF",
  },
  {
    name: "C",
    icon: "c",
    variant: "original",
    radius: 30,
    bg: "#A8B9CC",
    fg: "#1A1A1A",
  },
  {
    name: "Ruby",
    icon: "ruby",
    variant: "plain",
    radius: 30,
    bg: "#CC342D",
    fg: "#FFFFFF",
  },
  {
    name: "Kotlin",
    icon: "kotlin",
    variant: "plain",
    radius: 30,
    bg: "#7F52FF",
    fg: "#FFFFFF",
  },
  {
    name: "Python",
    icon: "python",
    variant: "plain",
    radius: 30,
    bg: "#3776AB",
    fg: "#FFFFFF",
  },
  {
    name: "PHP",
    icon: "php",
    variant: "plain",
    radius: 30,
    bg: "#777BB4",
    fg: "#FFFFFF",
  },
  {
    name: "Java",
    icon: "java",
    variant: "plain",
    radius: 30,
    bg: "#ED8B00",
    fg: "#FFFFFF",
  },
  {
    name: "C#",
    icon: "csharp",
    variant: "plain",
    radius: 30,
    bg: "#239120",
    fg: "#FFFFFF",
  },
  // Frontend
  {
    name: "HTML",
    icon: "html5",
    variant: "plain",
    radius: 30,
    bg: "#E34F26",
    fg: "#FFFFFF",
  },
  {
    name: "CSS",
    icon: "css3",
    variant: "plain",
    radius: 30,
    bg: "#1572B6",
    fg: "#FFFFFF",
  },
  {
    name: "jQuery",
    icon: "jquery",
    variant: "plain",
    radius: 30,
    bg: "#0769AD",
    fg: "#FFFFFF",
  },
  {
    name: "Tailwind",
    icon: "tailwindcss",
    variant: "original",
    radius: 30,
    bg: "#06B6D4",
    fg: "#FFFFFF",
  },
  {
    name: "JavaScript",
    icon: "javascript",
    variant: "plain",
    radius: 30,
    bg: "#F7DF1E",
    fg: "#1A1A1A",
  },
  // Full Stack
  {
    name: "SvelteKit",
    icon: "svelte",
    variant: "plain",
    radius: 30,
    bg: "#FF3E00",
    fg: "#FFFFFF",
  },
  {
    name: "TypeScript",
    icon: "typescript",
    variant: "plain",
    radius: 30,
    bg: "#3178C6",
    fg: "#FFFFFF",
  },
  {
    name: "Rails",
    icon: "rails",
    variant: "plain",
    radius: 30,
    bg: "#CC0000",
    fg: "#FFFFFF",
  },
  {
    name: "Laravel",
    icon: "laravel",
    variant: "original",
    radius: 30,
    bg: "#FF2D20",
    fg: "#FFFFFF",
  },
  {
    name: "Astro",
    icon: "astro",
    variant: "plain",
    radius: 30,
    bg: "#FF5D01",
    fg: "#FFFFFF",
  },
  // Databases
  {
    name: "SQLite",
    icon: "sqlite",
    variant: "plain",
    radius: 30,
    bg: "#003B57",
    fg: "#FFFFFF",
  },
  {
    name: "Postgres",
    icon: "postgresql",
    variant: "plain",
    radius: 30,
    bg: "#336791",
    fg: "#FFFFFF",
  },
  {
    name: "MariaDB",
    icon: "mariadb",
    variant: "original",
    radius: 30,
    bg: "#003545",
    fg: "#FFFFFF",
  },
  {
    name: "MySQL",
    icon: "mysql",
    variant: "original",
    radius: 30,
    bg: "#4479A1",
    fg: "#FFFFFF",
  },
  {
    name: "MongoDB",
    icon: "mongodb",
    variant: "plain",
    radius: 30,
    bg: "#47A248",
    fg: "#FFFFFF",
  },
  // Game Development
  {
    name: "Godot",
    icon: "godot",
    variant: "plain",
    radius: 30,
    bg: "#478CBF",
    fg: "#FFFFFF",
  },
  {
    name: "Bevy",
    icon: "bevyengine",
    variant: "plain",
    radius: 30,
    bg: "#232326",
    fg: "#FFFFFF",
  },
  {
    name: "Blender",
    icon: "blender",
    variant: "original",
    radius: 30,
    bg: "#E87D0D",
    fg: "#FFFFFF",
  },
  {
    name: "GameMaker",
    icon: null,
    variant: null,
    radius: 30,
    bg: "#8DC63F",
    fg: "#FFFFFF",
  },
  {
    name: "Unity",
    icon: "unity",
    variant: "plain",
    radius: 30,
    bg: "#222222",
    fg: "#FFFFFF",
  },
  // Shells
  {
    name: "Fish",
    icon: null,
    variant: null,
    radius: 30,
    bg: "#F2674A",
    fg: "#FFFFFF",
  },
  {
    name: "Nushell",
    icon: null,
    variant: null,
    radius: 30,
    bg: "#3E97A6",
    fg: "#FFFFFF",
  },
  {
    name: "Zsh",
    icon: "zsh",
    variant: "plain",
    radius: 30,
    bg: "#C5D928",
    fg: "#1A1A1A",
  },
  {
    name: "Bash",
    icon: "bash",
    variant: "plain",
    radius: 30,
    bg: "#293137",
    fg: "#FFFFFF",
  },
  {
    name: "PowerShell",
    icon: "powershell",
    variant: "plain",
    radius: 30,
    bg: "#012456",
    fg: "#FFFFFF",
  },
  // Operating Systems
  {
    name: "Arch",
    icon: "archlinux",
    variant: "plain",
    radius: 30,
    bg: "#1793D1",
    fg: "#FFFFFF",
  },
  {
    name: "Ubuntu",
    icon: "ubuntu",
    variant: "plain",
    radius: 30,
    bg: "#E95420",
    fg: "#FFFFFF",
  },
  {
    name: "Mint",
    icon: "linuxmint",
    variant: "plain",
    radius: 30,
    bg: "#87CF3E",
    fg: "#1A1A1A",
  },
  {
    name: "Debian",
    icon: "debian",
    variant: "plain",
    radius: 30,
    bg: "#A81D33",
    fg: "#FFFFFF",
  },
  {
    name: "Android",
    icon: "android",
    variant: "plain",
    radius: 30,
    bg: "#3DDC84",
    fg: "#1A1A1A",
  },
  {
    name: "Windows",
    icon: "windows8",
    variant: "original",
    radius: 30,
    bg: "#0078D7",
    fg: "#FFFFFF",
  },
  {
    name: "OSX",
    icon: "apple",
    variant: "original",
    radius: 30,
    bg: "#555555",
    fg: "#FFFFFF",
  },
  // Editors
  {
    name: "Helix",
    icon: null,
    variant: null,
    radius: 30,
    bg: "#7C37AD",
    fg: "#FFFFFF",
  },
  {
    name: "Neovim",
    icon: "neovim",
    variant: "plain",
    radius: 30,
    bg: "#57A143",
    fg: "#FFFFFF",
  },
  {
    name: "Vim",
    icon: "vim",
    variant: "plain",
    radius: 30,
    bg: "#019833",
    fg: "#FFFFFF",
  },
  {
    name: "VSCode",
    icon: "vscode",
    variant: "plain",
    radius: 30,
    bg: "#007ACC",
    fg: "#FFFFFF",
  },
  {
    name: "Android Studio",
    icon: "androidstudio",
    variant: "plain",
    radius: 30,
    bg: "#3DDC84",
    fg: "#1A1A1A",
  },
  {
    name: "JetBrains",
    icon: "jetbrains",
    variant: "plain",
    radius: 30,
    bg: "#000000",
    fg: "#FFFFFF",
  },
  // Other
  {
    name: "Tauri",
    icon: "tauri",
    variant: "plain",
    radius: 30,
    bg: "#FFC131",
    fg: "#1A1A1A",
  },
  {
    name: "WASM",
    icon: "wasm",
    variant: "original",
    radius: 30,
    bg: "#654FF0",
    fg: "#FFFFFF",
  },
  {
    name: "Appwrite",
    icon: "appwrite",
    variant: "original",
    radius: 30,
    bg: "#FD366E",
    fg: "#FFFFFF",
  },
  {
    name: "Flutter",
    icon: "flutter",
    variant: "plain",
    radius: 30,
    bg: "#54C5F8",
    fg: "#1A1A1A",
  },
  {
    name: "Lua",
    icon: "lua",
    variant: "plain",
    radius: 30,
    bg: "#000080",
    fg: "#FFFFFF",
  },
];
